import type { Metadata } from "next";
import { Geist, Inter, Train_One } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const trainOne = Train_One({
  variable: "--font-train-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Racing Standings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body
        className={`${geistSans.variable} ${interSans.variable} ${trainOne.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
